# Generated by Django 5.1.3 on 2024-11-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=1)),
                ('age', models.IntegerField(default=20)),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1)),
                ('hobby', models.CharField(choices=[('game', '게임'), ('golf', '골프'), ('swim', '수영'), ('run', '조깅')], max_length=5)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('gender__in', ['M', 'F'])), name='check_gender'), models.CheckConstraint(condition=models.Q(('hobby__in', ['game', 'golf', 'swim', 'run'])), name='check_hobby')],
            },
        ),
    ]
