# Generated by Django 5.1.3 on 2024-11-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='check_hobby',
        ),
        migrations.AlterField(
            model_name='student',
            name='hobby',
            field=models.CharField(max_length=20),
        ),
    ]
